### ISSUE TITLE
Cannot install gemsmith - Could not find a valid gem 'git_plus' (~> 0.4)

### ISSUE THREAD

**Issue by Quintasan** [bkuhlmann/gemsmith#11]
## Overview
Cannot install gemsmith using Ruby 3.0.5

It appears that the gem has been yanked according to https://rubygems.org/gems/git_plus

## Screenshots/Screencasts
```
jsonlinter on  master [?] 
❯ gem cert --add <(curl --compressed --location https://alchemists.io/gems.pem)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1158  100  1158    0     0   1002      0  0:00:01  0:00:01 --:--:--  1002
Added '/CN=brooke/DC=alchemists/DC=io'

jsonlinter on  master [?] 
❯ gem install gemsmith --trust-policy HighSecurity

ERROR:  Could not find a valid gem 'git_plus' (~> 0.4) (required by 'gemsmith' (>= 0)) in any repository
ERROR:  Possible alternatives: git-blur, git-plan, git-pulls, git_ls, git_push, gitius, gitploy, gplus, optplus

jsonlinter on  master [?] took 5s 
❯ ruby --version                                                                                      
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
```

## Steps to Recreate

See above

## Environment

OS: KDE neon 5.27 (basically Ubuntu 22.04)
Ruby: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
Gem version: 3.4.13

**Comment by bkuhlmann** [comment]
Hey Michał. :wave: Yeah, support for Git+ was removed over a year and a half ago with the introduction of [Rubysmith](https://alchemists.io/projects/rubysmith). This was done in Version 16.0.0 on 2022-01-26. Git+ has definitely been yanked and is completly replaced by [Gitt](https://alchemists.io/projects/gitt).

Please upgrade to Gemsmith 16.0.0 (which required Ruby 3.1.0). You'd be much better off upgrading to Gemsmith 20.3.0 (latest as of this writing) since I no longer support anything lower than Ruby 3.2.0.

Closing this issue is already fixed in the latest version.
